# -*- coding: utf-8 -*-
from __future__ import annotations

"""Public-boundary constants for EmlisAI Gate Recovery surfaces.

P0/P1 material only.

These constants make the current Gate Recovery material-surface lineage explicit
without changing the public API/RN contract or enforcing the public-boundary
runtime decision.  P2/P3 are expected to consume these constants to block
``diagnostic_recovery_surface`` candidates before they can become public
``comment_text``.
"""

from typing import Final

GATE_RECOVERY_PUBLIC_BOUNDARY_SCHEMA_VERSION: Final = (
    "cocolon.emlis.gate_recovery_public_boundary.v1"
)

CANDIDATE_SOURCE_KIND_COMPLETE_INITIAL_COMPOSER: Final = "complete_initial_composer"
CANDIDATE_SOURCE_KIND_LIMITED_COMPOSER: Final = "limited_composer"
CANDIDATE_SOURCE_KIND_LOW_INFORMATION_OBSERVATION_COMPOSER: Final = (
    "low_information_observation_composer"
)
CANDIDATE_SOURCE_KIND_SELF_DENIAL_SAFE_STATE_ANSWER: Final = "self_denial_safe_state_answer"
CANDIDATE_SOURCE_KIND_BOUNDED_REPAIRED_ORIGINAL_CANDIDATE: Final = (
    "bounded_repaired_original_candidate"
)
CANDIDATE_SOURCE_KIND_COMPLETE_SELF_REPAIR_CANDIDATE: Final = "complete_self_repair_candidate"
CANDIDATE_SOURCE_KIND_NORMAL_OBSERVATION_REBUILD_CANDIDATE: Final = (
    "normal_observation_rebuild_candidate"
)
CANDIDATE_SOURCE_KIND_GATE_RECOVERY_MATERIAL_SURFACE: Final = "gate_recovery_material_surface"
CANDIDATE_SOURCE_KIND_DIAGNOSTIC_RECOVERY_SURFACE: Final = "diagnostic_recovery_surface"
CANDIDATE_SOURCE_KIND_NONE: Final = "none"

PUBLIC_SURFACE_ROLE_PUBLIC_OBSERVATION: Final = "public_observation_candidate"
PUBLIC_SURFACE_ROLE_DIAGNOSTIC_RECOVERY: Final = "diagnostic_recovery_surface"
PUBLIC_SURFACE_ROLE_RECOVERY_PLAN_ONLY: Final = "recovery_plan_only"
PUBLIC_SURFACE_ROLE_BLOCKED_NO_PUBLIC_CANDIDATE: Final = "blocked_no_public_candidate"

GATE_RECOVERY_MATERIAL_SURFACE_MODEL: Final = "phase20_5_gate_recovery_material_surface"
POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_MODEL: Final = (
    "phase20_13_post_final_gate_recovery_material_surface"
)
GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHOD: Final = "phase20_5_gate_recovery_loop"
POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHOD: Final = (
    "phase20_13_post_final_gate_recovery_loop"
)
GATE_RECOVERY_LOOP_SOURCE_PHASE: Final = "Phase20-5_Gate_Recovery_Loop"
POST_FINAL_GATE_RECOVERY_SOURCE_PHASE: Final = "Phase20-13_Post_Final_Gate_Recovery"
RECOVERY_CONTEXT_PRE_PUBLIC_DISPLAY_GATE: Final = "pre_public_display_gate"
RECOVERY_CONTEXT_POST_FINAL_PRE_RETURN_GATE: Final = "post_final_pre_return_gate"
RECOVERY_CONTEXT_UNKNOWN: Final = "unknown"
SURFACE_GENERATION_METHOD_MATERIAL_BOUND_GENERIC_SURFACE: Final = "material_bound_generic_surface"
GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHODS: Final[frozenset[str]] = frozenset(
    {
        GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHOD,
        POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHOD,
    }
)
GATE_RECOVERY_MATERIAL_SURFACE_MODELS: Final[frozenset[str]] = frozenset(
    {
        GATE_RECOVERY_MATERIAL_SURFACE_MODEL,
        POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_MODEL,
    }
)

BLOCKER_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK: Final = (
    "gate_recovery_material_surface_public_leak"
)
BLOCKER_POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK: Final = (
    "post_final_gate_recovery_material_surface_public_leak"
)
BLOCKER_GATE_RECOVERY_DIAGNOSTIC_SURFACE_PROMOTED_TO_PUBLIC: Final = (
    "gate_recovery_diagnostic_surface_promoted_to_public"
)
BLOCKER_GATE_RECOVERY_INTERNAL_POLICY_SENTENCE_LEAK: Final = (
    "gate_recovery_internal_policy_sentence_leak"
)
BLOCKER_GATE_RECOVERY_TEMPLATE_META_FALSE_NEGATIVE: Final = (
    "gate_recovery_template_meta_false_negative"
)
BLOCKER_COMPOSER_DISABLED_RECOVERY_SURFACE_PUBLIC_SUBSTITUTION: Final = (
    "composer_disabled_recovery_surface_public_substitution"
)
BLOCKER_RECOVERY_SURFACE_SOURCE_LINEAGE_MISSING: Final = "recovery_surface_source_lineage_missing"
BLOCKER_PUBLIC_CANDIDATE_SOURCE_NOT_OPEN: Final = "public_candidate_source_not_open"
BLOCKER_BOUNDED_RECOVERY_PUBLIC_CANDIDATE_MISSING: Final = (
    "bounded_recovery_public_candidate_missing"
)
BLOCKER_NORMAL_OBSERVATION_REBUILD_CANDIDATE_MISSING: Final = (
    "normal_observation_rebuild_candidate_missing"
)

GATE_RECOVERY_PUBLIC_LEAK_BLOCKERS: Final[frozenset[str]] = frozenset(
    {
        BLOCKER_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK,
        BLOCKER_POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK,
        BLOCKER_GATE_RECOVERY_DIAGNOSTIC_SURFACE_PROMOTED_TO_PUBLIC,
        BLOCKER_GATE_RECOVERY_INTERNAL_POLICY_SENTENCE_LEAK,
        BLOCKER_GATE_RECOVERY_TEMPLATE_META_FALSE_NEGATIVE,
        BLOCKER_COMPOSER_DISABLED_RECOVERY_SURFACE_PUBLIC_SUBSTITUTION,
        BLOCKER_RECOVERY_SURFACE_SOURCE_LINEAGE_MISSING,
        BLOCKER_PUBLIC_CANDIDATE_SOURCE_NOT_OPEN,
        BLOCKER_BOUNDED_RECOVERY_PUBLIC_CANDIDATE_MISSING,
    }
)

ALLOWED_PUBLIC_CANDIDATE_SOURCE_KINDS: Final[frozenset[str]] = frozenset(
    {
        CANDIDATE_SOURCE_KIND_COMPLETE_INITIAL_COMPOSER,
        CANDIDATE_SOURCE_KIND_LIMITED_COMPOSER,
        CANDIDATE_SOURCE_KIND_LOW_INFORMATION_OBSERVATION_COMPOSER,
        CANDIDATE_SOURCE_KIND_SELF_DENIAL_SAFE_STATE_ANSWER,
        CANDIDATE_SOURCE_KIND_BOUNDED_REPAIRED_ORIGINAL_CANDIDATE,
        CANDIDATE_SOURCE_KIND_COMPLETE_SELF_REPAIR_CANDIDATE,
        CANDIDATE_SOURCE_KIND_NORMAL_OBSERVATION_REBUILD_CANDIDATE,
    }
)
FORBIDDEN_PUBLIC_CANDIDATE_SOURCE_KINDS: Final[frozenset[str]] = frozenset(
    {
        CANDIDATE_SOURCE_KIND_GATE_RECOVERY_MATERIAL_SURFACE,
        CANDIDATE_SOURCE_KIND_DIAGNOSTIC_RECOVERY_SURFACE,
        CANDIDATE_SOURCE_KIND_NONE,
    }
)


def gate_recovery_material_surface_blockers_for_model(composer_model: str) -> tuple[str, ...]:
    """Return the blocker tuple for a known Gate Recovery material-surface model.

    This helper is intentionally meta-only: it does not inspect or return body
    text, and it does not make the P2 public-boundary decision.
    """

    model = str(composer_model or "").strip()
    if model == POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_MODEL:
        return (
            BLOCKER_POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK,
            BLOCKER_GATE_RECOVERY_DIAGNOSTIC_SURFACE_PROMOTED_TO_PUBLIC,
        )
    if model == GATE_RECOVERY_MATERIAL_SURFACE_MODEL:
        return (
            BLOCKER_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK,
            BLOCKER_GATE_RECOVERY_DIAGNOSTIC_SURFACE_PROMOTED_TO_PUBLIC,
        )
    return ()


__all__ = [
    "ALLOWED_PUBLIC_CANDIDATE_SOURCE_KINDS",
    "BLOCKER_BOUNDED_RECOVERY_PUBLIC_CANDIDATE_MISSING",
    "BLOCKER_COMPOSER_DISABLED_RECOVERY_SURFACE_PUBLIC_SUBSTITUTION",
    "BLOCKER_GATE_RECOVERY_DIAGNOSTIC_SURFACE_PROMOTED_TO_PUBLIC",
    "BLOCKER_GATE_RECOVERY_INTERNAL_POLICY_SENTENCE_LEAK",
    "BLOCKER_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK",
    "BLOCKER_GATE_RECOVERY_TEMPLATE_META_FALSE_NEGATIVE",
    "BLOCKER_POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_PUBLIC_LEAK",
    "BLOCKER_NORMAL_OBSERVATION_REBUILD_CANDIDATE_MISSING",
    "BLOCKER_PUBLIC_CANDIDATE_SOURCE_NOT_OPEN",
    "BLOCKER_RECOVERY_SURFACE_SOURCE_LINEAGE_MISSING",
    "CANDIDATE_SOURCE_KIND_BOUNDED_REPAIRED_ORIGINAL_CANDIDATE",
    "CANDIDATE_SOURCE_KIND_COMPLETE_INITIAL_COMPOSER",
    "CANDIDATE_SOURCE_KIND_COMPLETE_SELF_REPAIR_CANDIDATE",
    "CANDIDATE_SOURCE_KIND_DIAGNOSTIC_RECOVERY_SURFACE",
    "CANDIDATE_SOURCE_KIND_GATE_RECOVERY_MATERIAL_SURFACE",
    "CANDIDATE_SOURCE_KIND_LIMITED_COMPOSER",
    "CANDIDATE_SOURCE_KIND_LOW_INFORMATION_OBSERVATION_COMPOSER",
    "CANDIDATE_SOURCE_KIND_NONE",
    "CANDIDATE_SOURCE_KIND_NORMAL_OBSERVATION_REBUILD_CANDIDATE",
    "CANDIDATE_SOURCE_KIND_SELF_DENIAL_SAFE_STATE_ANSWER",
    "FORBIDDEN_PUBLIC_CANDIDATE_SOURCE_KINDS",
    "GATE_RECOVERY_LOOP_SOURCE_PHASE",
    "GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHOD",
    "GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHODS",
    "GATE_RECOVERY_MATERIAL_SURFACE_MODEL",
    "GATE_RECOVERY_MATERIAL_SURFACE_MODELS",
    "GATE_RECOVERY_PUBLIC_BOUNDARY_SCHEMA_VERSION",
    "GATE_RECOVERY_PUBLIC_LEAK_BLOCKERS",
    "POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_GENERATION_METHOD",
    "POST_FINAL_GATE_RECOVERY_MATERIAL_SURFACE_MODEL",
    "POST_FINAL_GATE_RECOVERY_SOURCE_PHASE",
    "PUBLIC_SURFACE_ROLE_BLOCKED_NO_PUBLIC_CANDIDATE",
    "PUBLIC_SURFACE_ROLE_DIAGNOSTIC_RECOVERY",
    "PUBLIC_SURFACE_ROLE_PUBLIC_OBSERVATION",
    "PUBLIC_SURFACE_ROLE_RECOVERY_PLAN_ONLY",
    "RECOVERY_CONTEXT_POST_FINAL_PRE_RETURN_GATE",
    "RECOVERY_CONTEXT_PRE_PUBLIC_DISPLAY_GATE",
    "RECOVERY_CONTEXT_UNKNOWN",
    "SURFACE_GENERATION_METHOD_MATERIAL_BOUND_GENERIC_SURFACE",
    "gate_recovery_material_surface_blockers_for_model",
]
