# -*- coding: utf-8 -*-
from __future__ import annotations

"""Step0 Runtime Surface Quality contract inventory for EmlisAI.

This inventory starts the post ProductGate Measurement phase and keeps the
phase meta-only.  Step12 closes the Runtime Surface Quality sequence as a meta-only Exit Gate.
It preserves next branch, release blockers, coverage gaps, and QA gaps, but
still never stores raw input bodies, public ``comment_text`` bodies, or
unsupported replacement observation sentences.
"""

import json
from collections.abc import Mapping
from typing import Any

RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_VERSION = (
    "emlis.runtime_surface_quality_contract_inventory.v1"
)
RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_STEP = "Step0_Baseline_Contract_Inventory"
RUNTIME_SURFACE_QUALITY_SCOPE = "Post ProductGate Measurement Runtime Surface Quality Step0-12"

_FORBIDDEN_TEXT_PAYLOAD_KEYS = {
    "raw_input",
    "rawInput",
    "raw_text",
    "rawText",
    "source_text",
    "sourceText",
    "input",
    "input_text",
    "inputText",
    "user_input",
    "userInput",
    "memo",
    "memo_text",
    "memoText",
    "current_input",
    "currentInput",
    "comment_text",
    "commentText",
    "input_feedback_comment",
    "inputFeedbackComment",
    "public_comment_text",
    "candidate_comment_text",
    "reply_text",
    "replyText",
    "surface_text",
    "realized_text",
    "body",
    "text",
}

_FORBIDDEN_TRUE_FLAGS = (
    "raw_input_included",
    "raw_text_included",
    "comment_text_included",
    "comment_text_body_included",
    "response_shape_changed",
    "public_response_key_change",
    "api_route_changed",
    "db_physical_name_changed",
    "rn_visible_contract_changed",
    "rn_visible_title_changed",
    "display_gate_relaxed",
    "grounding_gate_relaxed",
    "template_gate_relaxed",
    "reader_gate_relaxed",
    "gate_relaxed",
    "public_release_applied",
    "product_gate_public_release_applied",
    "product_quality_released",
    "product_gate_achieved",
    "product_gate_reached",
    "fixture_text_used_for_runtime_branching",
    "runtime_branching_uses_fixture_strings",
    "external_ai_used",
    "local_llm_used",
    "fixed_sentence_template_used",
    "fixed_fallback_used",
    "surface_text_repaired_by_step6",
    "fixed_completed_sentence_template_added",
    "input_specific_surface_branch_added",
    "surface_realizer_2_1_anti_template_uses_fixture_strings",
    "surface_realizer_2_1_anti_template_relaxes_gate",
    "rn_complete_dedicated_display_branch_added",
    "complete_dedicated_rn_display_branch_added",
    "phrase_unit_grammar_normalizer_relaxes_gate",
    "phrase_unit_grammar_normalizer_adds_fixed_sentence_templates",
    "phrase_unit_grammar_normalizer_uses_input_specific_branching",
    "unsupported_completion_added_by_phrase_unit_grammar",
    "meaning_added_by_phrase_unit_grammar",
    "surface_text_repaired_by_step8",
    "tone_engine_2_1_relaxes_gate",
    "tone_engine_2_1_uses_fixture_strings",
    "fixed_sentence_template_added_by_tone",
    "fixed_sentence_template_used_by_tone",
    "input_specific_tone_branch_added",
    "meaning_added_by_tone_engine_2_1",
    "surface_text_repaired_by_step9",
    "surface_aware_self_repair_meaning_added",
    "surface_aware_self_repair_gate_relaxed",
    "surface_aware_self_repair_uses_fixture_strings",
    "unsupported_sentence_added_by_surface_repair",
    "fixed_completed_sentence_template_added_by_step10",
    "input_specific_surface_branch_added_by_step10",
    "surface_aware_self_repair_changes_public_contract",
    "blind_qa_candidate_includes_text",
    "blind_qa_review_includes_text",
    "long_run_uses_comment_text",
    "long_run_uses_raw_input",
    "read_feeling_auto_estimation_allowed",
    "runtime_surface_exit_gate_changes_public_contract",
    "runtime_surface_exit_gate_relaxes_gate",
    "runtime_surface_exit_gate_applies_public_release",
    "runtime_surface_exit_gate_declares_product_gate",
)


def _contains_forbidden_text_payload_key(value: Any) -> bool:
    if isinstance(value, Mapping):
        for key, item in value.items():
            if str(key) in _FORBIDDEN_TEXT_PAYLOAD_KEYS:
                return True
            if _contains_forbidden_text_payload_key(item):
                return True
        return False
    if isinstance(value, (list, tuple, set)):
        return any(_contains_forbidden_text_payload_key(item) for item in value)
    return False


def assert_runtime_surface_quality_contract_inventory_meta_only(
    value: Mapping[str, Any],
    *,
    source: str = "runtime_surface_quality_contract_inventory",
) -> None:
    """Reject raw text/comment bodies and any contract-relaxation marker."""

    if _contains_forbidden_text_payload_key(value):
        raise ValueError(f"{source} must stay meta-only and must not include text payload keys")
    for key in _FORBIDDEN_TRUE_FLAGS:
        if value.get(key) is True:
            raise ValueError(f"{source} violates fixed contract: {key}=true")


def build_runtime_surface_quality_contract_inventory() -> dict[str, Any]:
    """Return Step0 baseline contracts for the Runtime Surface Quality phase."""

    inventory: dict[str, Any] = {
        "version": RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_VERSION,
        "source_step": RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_STEP,
        "step": RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_STEP,
        "status": "fixed",
        "scope": RUNTIME_SURFACE_QUALITY_SCOPE,
        "phase": "post_product_gate_measurement_runtime_surface_quality",
        "runtime_surface_quality_measurement_only": True,
        "step0_baseline_contract_inventory_ready": True,
        "step1_runtime_surface_source_lock_required": True,
        "step1_runtime_surface_source_lock_ready": False,
        "step2_surface_signature_measurement_required": True,
        "step2_surface_signature_measurement_ready": False,
        "step3_scorecard_surface_metrics_connection_required": True,
        "step3_scorecard_surface_metrics_connection_ready": False,
        "step4_coverage_runtime_baseline_required": True,
        "step4_coverage_runtime_baseline_ready": False,
        "step5_branch_resolver_required": True,
        "step5_branch_resolver_ready": False,
        "step5_runtime_surface_quality_branch_resolver_required": True,
        "step5_runtime_surface_quality_branch_resolver_ready": False,
        "step6_complete_runtime_activation_branch_required": True,
        "step6_complete_runtime_activation_branch_ready": False,
        "step6_runtime_surface_complete_activation_branch_required": True,
        "step6_runtime_surface_complete_activation_branch_ready": False,
        "step6_complete_runtime_activation_meta_only": True,
        "step7_surface_realizer_2_1_anti_template_required": True,
        "step7_surface_realizer_2_1_anti_template_ready": False,
        "step7_surface_realizer_anti_template_required": True,
        "step7_surface_realizer_anti_template_ready": False,
        "step7_surface_realizer_anti_template_meta_only": True,
        "step8_phrase_unit_grammar_normalizer_required": True,
        "step8_phrase_unit_grammar_normalizer_ready": False,
        "step8_phrase_unit_grammar_normalizer_meta_only": True,
        "phrase_unit_grammar_normalizer_material_stage_only": True,
        "step9_tone_engine_2_1_required": True,
        "step9_tone_engine_2_1_ready": False,
        "step9_tone_engine_2_1_meta_only": True,
        "tone_engine_2_1_surface_constraint_only": True,
        "tone_engine_2_1_blind_qa_required_for_completion": True,
        "step10_surface_aware_self_repair_required": True,
        "step10_surface_aware_self_repair_ready": False,
        "step10_surface_aware_self_repair_meta_only": True,
        "surface_aware_self_repair_plan_surface_only": True,
        "surface_aware_self_repair_max_attempts_required": True,
        "surface_aware_self_repair_fail_closed_on_max_attempts": True,
        "step11_blind_qa_long_run_required": True,
        "step11_blind_qa_long_run_ready": False,
        "step11_blind_qa_long_run_meta_only": True,
        "step11_blind_qa_candidate_bodyless": True,
        "step11_long_run_uses_surface_signature_only": True,
        "step11_read_feeling_requires_blind_qa": True,
        "step12_exit_gate_required": True,
        "step12_exit_gate_ready": False,
        "step12_exit_gate_meta_only": True,
        "step12_exit_gate_handoff_only": True,
        "step12_exit_gate_public_release_applied": False,
        "step12_exit_gate_product_gate_achieved": False,
        "step12_exit_gate_preserves_release_blockers": True,
        "step12_exit_gate_preserves_coverage_gaps": True,
        "step12_exit_gate_preserves_qa_gaps": True,
        "coverage_runtime_baseline_only": True,
        "complete_runtime_activation_branch_only": True,
        "surface_realizer_anti_template_only": True,
        "steps_in_scope": [
            "Step0: Baseline / Contract Inventory",
            "Step1: Runtime Surface Source Lock",
            "Step2: Surface Signature Measurement",
            "Step3: Scorecard Surface Metrics connection",
            "Step4: Coverage Runtime Baseline",
            "Step5: Branch Resolver",
            "Step6: Complete Runtime Activation Branch",
            "Step7: Surface Realizer 2.1 Anti-Template",
            "Step8: PhraseUnit Grammar Normalizer",
            "Step9: Tone Engine 2.1",
            "Step10: Surface-aware Self-Repair",
            "Step11: Blind QA / Long-run",
            "Step12: Exit Gate",
        ],
        "steps_out_of_scope": [
            "public release application after Runtime Surface Quality Exit Gate",
            "Product Gate achievement declaration from Step12",
        ],
        "non_targets": [
            "RN display condition relaxation",
            "API response key rename",
            "DB physical rename or write-path change",
            "Display / Reader / Grounding / Template Gate relaxation",
            "Product Gate achievement declaration",
            "public release application",
            "raw input body logging",
            "public comment_text body logging",
            "fixed fallback observation sentence addition",
            "surface wording repair before runtime source is locked",
            "surface wording repair outside complete_initial source-lock branch",
            "unsupported grammar completion addition",
            "complete-specific RN display branch addition",
            "tone repair by fixed completed sentence",
            "tone completion judged by machine metrics alone",
            "input-specific tone branch addition",
            "Blind QA candidate body storage",
            "Long-run similarity based on comment_text body",
            "Product Gate ready without Blind QA / Long-run material",
        ],
        "contract_locks": [
            {
                "contract_id": "runtime_surface_quality_measurement_only_boundary",
                "locked": True,
                "description": "Step0-12 inventories baseline contracts, locks runtime source, measures surface signature, connects scorecard metrics, builds coverage runtime baseline, resolves the next target branch, verifies Complete runtime activation, applies Surface Realizer 2.1 Anti-Template, normalizes PhraseUnit grammar, connects Tone Engine 2.1, adds Surface-aware Self-Repair, connects Blind QA / Long-run, and closes the Runtime Surface Quality Exit Gate without declaring Product Gate achieved.",
            },
            {
                "contract_id": "rn_passed_only_modal_contract",
                "locked": True,
                "description": "Emlis modal display remains passed-only with body present; RN runtime files are not modified.",
            },
            {
                "contract_id": "api_response_key_stability_boundary",
                "locked": True,
                "description": "Existing public response keys are not renamed or removed.",
            },
            {
                "contract_id": "db_physical_name_boundary",
                "locked": True,
                "description": "DB physical names and persistence contracts are not changed.",
            },
            {
                "contract_id": "gate_fail_closed_boundary",
                "locked": True,
                "description": "Display, Reader, Grounding, and Template gates are not relaxed.",
            },
            {
                "contract_id": "meta_only_raw_body_boundary",
                "locked": True,
                "description": "Runtime Surface Quality diagnostics carry meta only, never raw input or comment_text body.",
            },
            {
                "contract_id": "product_gate_not_achieved_boundary",
                "locked": True,
                "description": "This phase is preparation for quality branching, not Product Gate achievement.",
            },
            {
                "contract_id": "runtime_source_before_surface_fix_boundary",
                "locked": True,
                "description": "Surface/Tone repairs must wait until the displayed observation source is locked.",
            },
            {
                "contract_id": "complete_runtime_activation_before_surface_repair_boundary",
                "locked": True,
                "description": "If runtime source is limited/A1 equivalent, complete_initial entry AP0, rollout, registry, and source-lock alignment must be confirmed before Surface, Grammar, or Tone repair.",
            },
            {
                "contract_id": "surface_realizer_2_1_anti_template_boundary",
                "locked": True,
                "description": "Surface Realizer 2.1 may change grammar-part selection for complete_initial only; it must not add fixed completed observations, input-specific branches, Gate relaxation, public response key changes, DB changes, or RN display branches.",
            },
            {
                "contract_id": "phrase_unit_grammar_normalizer_material_stage_boundary",
                "locked": True,
                "description": "Step8 normalizes PhraseUnit grammar at material stage only, classifies unsafe fragments as drop/rephrase/defer, does not add unsupported meaning, and does not relax Gate, API, DB, or RN contracts.",
            },
            {
                "contract_id": "tone_engine_2_1_boundary",
                "locked": True,
                "description": "Step9 Tone Engine 2.1 constrains distance, diagnosis, advice, genericness, and ending repetition. It does not add fixed user-facing observation text, does not infer read-feeling from machine metrics, and does not relax Gate, API, DB, or RN contracts.",
            },
            {
                "contract_id": "surface_aware_self_repair_boundary",
                "locked": True,
                "description": "Step10 converts measured surface reasons into bounded Complete self-repair targets. It may re-plan or adjust surface artifacts only, preserves must_keep evidence and relation bindings, stops at max attempts, and fail-closes without Gate, API, DB, RN, public release, fixed sentence, or meaning expansion changes.",
            },
            {
                "contract_id": "blind_qa_long_run_boundary",
                "locked": True,
                "description": "Step11 builds Blind QA candidates from row id / coverage / classification and checks long-run surface-signature diversity. It never stores raw input or comment_text bodies, never derives read-feeling from machine metrics, and never applies Product Gate or public release.",
            },
            {
                "contract_id": "runtime_surface_quality_step12_exit_gate_boundary",
                "locked": True,
                "description": "Step12 adds runtime_surface_quality_exit_gate as a meta-only handoff. It preserves next branch, release blockers, coverage gaps, and QA gaps, but never applies public release, declares Product Gate, changes API/RN/DB contracts, or relaxes gates.",
            },
        ],
        "required_step1_meta_keys": [
            "runtime_surface_source_lock.schema_version",
            "runtime_surface_source_lock.trace_id",
            "runtime_surface_source_lock.emotion_log_id",
            "runtime_surface_source_lock.observation_status",
            "runtime_surface_source_lock.backend_comment_text_present",
            "runtime_surface_source_lock.backend_comment_text_length",
            "runtime_surface_source_lock.display_confirmed",
            "runtime_surface_source_lock.coverage_group",
            "runtime_surface_source_lock.composer_requested",
            "runtime_surface_source_lock.composer_resolved",
            "runtime_surface_source_lock.composer_source",
            "runtime_surface_source_lock.composer_model",
            "runtime_surface_source_lock.complete_initial_client_used",
            "runtime_surface_source_lock.limited_reader_repair_applied",
            "runtime_surface_source_lock.sentence_plan_version",
            "runtime_surface_source_lock.surface_realizer_version",
            "runtime_surface_source_lock.tone_policy_version",
            "runtime_surface_source_lock.self_repair_version",
            "runtime_surface_source_lock.surface_signature_id",
            "surface_quality_signature.schema_version",
            "surface_quality_signature.surface_signature_id",
            "surface_quality_signature.line_role_sequence",
            "surface_quality_signature.connector_key_sequence",
            "surface_quality_signature.predicate_key_sequence",
            "surface_quality_signature.ending_key_sequence",
            "surface_quality_signature.generic_center_phrase_count",
            "surface_quality_signature.same_connector_run_max",
            "surface_quality_signature.same_ending_family_count",
            "surface_quality_signature.malformed_nominalization_risk",
            "surface_quality_signature.raw_echo_risk",
            "surface_quality_signature.template_major",
            "surface_quality_signature.raw_text_included",
            "surface_quality_signature.comment_text_body_included",
            "product_quality_scorecard.surface_signature_repeat_rate",
            "product_quality_scorecard.connector_repetition_rate",
            "product_quality_scorecard.grammar_warning_rate",
            "product_quality_scorecard.coverage_surface_diversity_rate",
            "product_quality_scorecard.surface_template_major_count",
            "product_quality_scorecard.coverage_runtime_baseline.version",
            "product_quality_scorecard.coverage_runtime_baseline.required_coverage_groups",
            "product_quality_scorecard.coverage_runtime_baseline.coverage_group_rows",
            "product_quality_scorecard.coverage_runtime_baseline.by_coverage_group",
            "product_quality_scorecard.coverage_runtime_baseline.missing_coverage_groups",
            "product_quality_scorecard.coverage_runtime_baseline.coverage_group_missing_count",
            "product_quality_scorecard.coverage_runtime_baseline.fixture_text_used_for_runtime_branching",
            "runtime_surface_quality_branch.version",
            "runtime_surface_quality_branch.target_layer",
            "runtime_surface_quality_branch.branch_reasons",
            "runtime_surface_quality_branch.repair_allowed",
            "runtime_surface_quality_branch.requires_diagnostic_enrichment",
            "runtime_surface_quality_branch.runtime_branching_uses_fixture_strings",
            "runtime_surface_quality_branch.fixture_text_used_for_runtime_branching",
            "runtime_surface_complete_activation_branch.version",
            "runtime_surface_complete_activation_branch.activation_branch_required",
            "runtime_surface_complete_activation_branch.activation_status",
            "runtime_surface_complete_activation_branch.complete_initial_requested",
            "runtime_surface_complete_activation_branch.complete_initial_resolved",
            "runtime_surface_complete_activation_branch.complete_initial_source_lock_aligned",
            "runtime_surface_complete_activation_branch.complete_initial_resolution_safe_to_measure",
            "runtime_surface_complete_activation_branch.entry_ap0_or_rollout_required_before_surface_repair",
            "runtime_surface_complete_activation_branch.surface_repair_deferred_until_complete_runtime_measurable",
            "surface_realizer.surface_realizer_2_1_anti_template_version",
            "surface_realizer.surface_anti_template_guard_passed",
            "surface_realizer.surface_anti_template_report.generic_center_opening_count",
            "surface_realizer.surface_anti_template_report.same_connector_key_run_max",
            "surface_realizer.surface_anti_template_report.same_connector_family_run_max",
            "surface_realizer.surface_anti_template_report.same_predicate_family_count",
            "surface_realizer.surface_anti_template_report.same_ending_family_count",
            "surface_realizer.surface_realizer_2_1_anti_template_uses_fixture_strings",
            "surface_realizer.surface_realizer_2_1_anti_template_adds_completed_sentence_templates",
            "runtime_surface_source_lock.raw_text_included",
            "runtime_surface_source_lock.comment_text_body_included",
            "complete_surface_realizer.surface_realizer_anti_template_version",
            "complete_surface_realizer.surface_realizer_anti_template_policy_version",
            "complete_surface_realizer.surface_realizer_2_1_anti_template_applied",
            "complete_surface_realizer.surface_realizer_anti_template_report.same_connector_family_run_max",
            "complete_surface_realizer.surface_realizer_anti_template_report.same_predicate_family_count",
            "complete_surface_realizer.surface_realizer_anti_template_report.generic_center_opening_count",
            "complete_surface_realizer.surface_realizer_anti_template_report.anti_template_major_detected",
            "complete_surface_realizer.surface_realizer_anti_template_report.completion_sentence_template_used",
            "complete_surface_realizer.surface_realizer_anti_template_report.input_specific_template_used",
            "complete_surface_realizer.surface_realizer_anti_template_report.raw_input_included",
            "complete_material_service.phrase_unit_grammar_normalizer_version",
            "complete_material_service.phrase_unit_grammar_normalizer_step",
            "complete_material_service.grammar_warning_codes",
            "complete_material_service.phrase_unit_grammar_normalizer_report",
            "surface_quality_signature.phrase_unit_grammar_warning_codes",
            "product_quality_scorecard.phrase_unit_grammar_warning_codes",
            "tone_engine_2_1_report.tone_engine_2_1_version",
            "tone_engine_2_1_report.tone_guard_major_count",
            "tone_engine_2_1_report.tone_guard_reasons",
            "tone_engine_2_1_report.tone_safety_major_count",
            "tone_engine_2_1_report.tone_distance_major_count",
            "tone_engine_2_1_report.tone_naturalness_major_count",
            "tone_engine_2_1_report.machine_metrics_used_for_read_feeling",
            "tone_engine_2_1_report.read_feeling_auto_filled_from_machine_metrics",
            "tone_engine_2_1_report.comment_text_body_included",
            "product_quality_scorecard.tone_engine_2_1_major_count",
            "runtime_surface_self_repair.version",
            "runtime_surface_self_repair.step",
            "runtime_surface_self_repair.surface_aware_self_repair_targets",
            "runtime_surface_self_repair.surface_reason_to_repair_target_map",
            "runtime_surface_self_repair.repair_trace_v2_count",
            "runtime_surface_self_repair.repair_attempt_count",
            "runtime_surface_self_repair.repair_success_count",
            "runtime_surface_self_repair.meaning_added",
            "runtime_surface_self_repair.gate_relaxed",
            "product_quality_scorecard.runtime_surface_self_repair_attempt_count",
            "product_quality_scorecard.runtime_surface_self_repair_success_count",
            "runtime_surface_blind_qa_long_run.version",
            "runtime_surface_blind_qa_long_run.step",
            "runtime_surface_blind_qa_long_run.blind_qa_candidates",
            "runtime_surface_blind_qa_long_run.long_run_signature_diversity",
            "runtime_surface_blind_qa_long_run.long_run_surface_signature_diversity_rate",
            "runtime_surface_blind_qa_long_run.long_run_surface_signature_repeat_detected",
            "runtime_surface_blind_qa_long_run.machine_metrics_used_for_read_feeling",
            "runtime_surface_blind_qa_long_run.read_feeling_auto_filled_from_machine_metrics",
            "product_quality_scorecard.step11_blind_qa_long_run_ready",
            "product_quality_scorecard.long_run_surface_signature_diversity_rate",
            "runtime_surface_quality_exit_gate.version",
            "runtime_surface_quality_exit_gate.step",
            "runtime_surface_quality_exit_gate.next_branch",
            "runtime_surface_quality_exit_gate.release_blockers",
            "runtime_surface_quality_exit_gate.coverage_gaps",
            "runtime_surface_quality_exit_gate.qa_gaps",
            "runtime_surface_quality_exit_gate.product_gate_achieved",
            "runtime_surface_quality_exit_gate.public_release_applied",
        ],
        "allowed_touch_files": [
            "ai/services/ai_inference/emlis_ai_runtime_surface_quality_contract_inventory.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_source_lock.py",
            "ai/services/ai_inference/emlis_ai_complete_surface_quality_signature.py",
            "ai/services/ai_inference/emlis_ai_complete_reply_diagnostics_service.py",
            "ai/services/ai_inference/emlis_ai_reply_service.py",
            "ai/services/ai_inference/emlis_ai_complete_product_quality_measurement_connection.py",
            "ai/services/ai_inference/emlis_ai_complete_product_quality_scorecard_service.py",
            "ai/services/ai_inference/emlis_ai_complete_release_ladder_service.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_coverage_baseline.py",
            "ai/services/ai_inference/emlis_ai_complete_surface_quality_branching.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_complete_activation_branch.py",
            "ai/services/ai_inference/emlis_ai_composer_client_registry.py",
            "ai/services/ai_inference/emlis_ai_ap0_migration_decision_service.py",
            "ai/services/ai_inference/emlis_ai_complete_surface_realizer.py",
            "ai/services/ai_inference/emlis_ai_complete_surface_realizer_anti_template.py",
            "ai/services/ai_inference/emlis_ai_complete_sentence_planner.py",
            "ai/services/ai_inference/emlis_ai_relation_surface_contract.py",
            "ai/services/ai_inference/emlis_ai_complete_scorecard_service.py",
            "ai/services/ai_inference/emlis_ai_coverage_matrix_service.py",
            "ai/services/ai_inference/emlis_ai_phrase_unit_grammar_normalizer.py",
            "ai/services/ai_inference/emlis_ai_complete_material_service.py",
            "ai/services/ai_inference/emlis_ai_phrase_shaping_service.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_tone_engine_2_1.py",
            "ai/services/ai_inference/emlis_ai_complete_tone_policy.py",
            "ai/services/ai_inference/emlis_ai_reply_final_review_service.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_self_repair.py",
            "ai/services/ai_inference/emlis_ai_complete_self_repair_service.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_blind_qa_long_run.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_exit_gate.py",
            "ai/services/ai_inference/emlis_ai_long_term_quality_service.py",
            "ai/services/ai_inference/emlis_ai_runtime_surface_self_repair.py",
            "ai/services/ai_inference/emlis_ai_complete_self_repair_service.py",
            "ai/services/ai_inference/emlis_ai_complete_surface_realizer.py",
            "ai/services/ai_inference/emlis_ai_complete_surface_realizer_anti_template.py",
            "ai/services/ai_inference/emlis_ai_complete_sentence_planner.py",
            "ai/services/ai_inference/emlis_ai_relation_surface_contract.py",
            "ai/tests/test_emlis_ai_runtime_surface_quality_contract_inventory_step0.py",
            "ai/tests/test_emlis_ai_runtime_surface_source_lock_step1.py",
            "ai/tests/test_emlis_ai_complete_surface_quality_signature_step2.py",
            "ai/tests/test_emlis_ai_runtime_surface_scorecard_metrics_step3.py",
            "ai/tests/test_emlis_ai_runtime_surface_coverage_baseline_step4.py",
            "ai/tests/test_emlis_ai_runtime_surface_quality_branching_step5.py",
            "ai/tests/test_emlis_ai_runtime_surface_complete_activation_branch_step6.py",
            "ai/tests/test_emlis_ai_runtime_surface_realizer_anti_template_step7.py",
            "ai/tests/test_emlis_ai_complete_initial_entry_route.py",
            "ai/tests/test_emlis_ai_runtime_surface_realizer_anti_template_step7.py",
            "ai/tests/test_emlis_ai_complete_surface_realizer_v2.py",
            "ai/tests/test_emlis_ai_complete_surface_variation_v2.py",
            "ai/tests/test_emlis_ai_runtime_surface_phrase_unit_grammar_normalizer_step8.py",
            "ai/tests/test_emlis_ai_phrase_grammar_guard.py",
            "ai/tests/test_emlis_ai_complete_material_service.py",
            "ai/tests/test_emlis_ai_runtime_surface_tone_engine_2_1_step9.py",
            "ai/tests/test_emlis_ai_runtime_surface_self_repair_step10.py",
            "ai/tests/test_emlis_ai_runtime_surface_blind_qa_long_run_step11.py",
            "ai/tests/test_emlis_ai_runtime_surface_exit_gate_step12.py",
        ],
        "rn_runtime_files_modified_by_runtime_surface_quality": False,
        "db_physical_rename_allowed": False,
        "api_response_key_change_allowed": False,
        "rn_visible_contract_change_allowed": False,
        "gate_relaxation_allowed": False,
        "surface_text_repair_allowed_in_step0_1": False,
        "surface_text_repair_allowed_in_step0_2": False,
        "surface_text_repair_allowed_in_step0_3": False,
        "surface_text_repair_allowed_in_step0_4": False,
        "surface_text_repair_allowed_in_step0_5": False,
        "surface_text_repair_allowed_in_step0_6": False,
        "surface_realizer_anti_template_allowed_in_step7": True,
        "surface_realizer_anti_template_repairs_surface_text_only": True,
        "phrase_unit_grammar_normalizer_allowed_in_step8": True,
        "phrase_unit_grammar_normalizer_material_stage_only": True,
        "phrase_unit_grammar_normalizer_adds_unsupported_meaning": False,
        "phrase_unit_grammar_normalizer_adds_fixed_sentence_templates": False,
        "phrase_unit_grammar_normalizer_uses_input_specific_branching": False,
        "phrase_unit_grammar_normalizer_relaxes_gate": False,
        "surface_text_repaired_by_step8": False,
        "unsupported_completion_added_by_phrase_unit_grammar": False,
        "meaning_added_by_phrase_unit_grammar": False,
        "tone_engine_2_1_allowed_in_step9": True,
        "tone_engine_2_1_surface_constraint_only": True,
        "tone_engine_2_1_changes_public_contract": False,
        "tone_engine_2_1_relaxes_gate": False,
        "tone_engine_2_1_uses_fixture_strings": False,
        "fixed_sentence_template_added_by_tone": False,
        "input_specific_tone_branch_added": False,
        "meaning_added_by_tone_engine_2_1": False,
        "surface_text_repaired_by_step9": False,
        "machine_metrics_used_for_read_feeling": False,
        "read_feeling_auto_filled_from_machine_metrics": False,
        "tone_completion_requires_blind_qa": True,
        "surface_aware_self_repair_allowed_in_step10": True,
        "surface_aware_self_repair_replans_surface_only": True,
        "surface_aware_self_repair_fail_closed_on_max_attempts": True,
        "surface_aware_self_repair_changes_public_contract": False,
        "surface_aware_self_repair_relaxes_gate": False,
        "blind_qa_long_run_allowed_in_step11": True,
        "blind_qa_candidate_includes_text": False,
        "blind_qa_review_includes_text": False,
        "long_run_uses_comment_text": False,
        "long_run_uses_raw_input": False,
        "read_feeling_auto_estimation_allowed": False,
        "runtime_surface_exit_gate_allowed_in_step12": True,
        "runtime_surface_exit_gate_handoff_only": True,
        "runtime_surface_exit_gate_preserves_release_blockers": True,
        "runtime_surface_exit_gate_preserves_coverage_gaps": True,
        "runtime_surface_exit_gate_preserves_qa_gaps": True,
        "runtime_surface_exit_gate_changes_public_contract": False,
        "runtime_surface_exit_gate_relaxes_gate": False,
        "runtime_surface_exit_gate_applies_public_release": False,
        "runtime_surface_exit_gate_declares_product_gate": False,
        "surface_aware_self_repair_meaning_added": False,
        "surface_aware_self_repair_uses_fixture_strings": False,
        "unsupported_sentence_added_by_surface_repair": False,
        "fixed_completed_sentence_template_added_by_step10": False,
        "input_specific_surface_branch_added_by_step10": False,
        "surface_realizer_anti_template_changes_public_contract": False,
        "surface_realizer_anti_template_relaxes_gate": False,
        "surface_realizer_anti_template_adds_fixed_sentence_templates": False,
        "surface_realizer_anti_template_uses_input_specific_branching": False,
        "surface_realizer_anti_template_uses_external_ai": False,
        "complete_runtime_activation_repairs_surface_text": False,
        "complete_runtime_activation_changes_public_contract": False,
        "complete_runtime_activation_adds_rn_display_branch": False,
        "complete_runtime_activation_relaxes_entry_ap0": False,
        "complete_runtime_activation_relaxes_gate": False,
        "branch_resolver_repairs_surface_text": False,
        "branch_resolver_changes_public_contract": False,
        "scorecard_surface_metrics_connection_only": True,
        "coverage_runtime_baseline_only": True,
        "coverage_group_missing_falls_back_to_short_daily": False,
        "fixture_text_used_for_runtime_branching": False,
        "runtime_branching_uses_fixture_strings": False,
        "product_gate_achieved": False,
        "public_release_applied": False,
        "response_shape_changed": False,
        "public_response_key_change": False,
        "api_route_changed": False,
        "db_physical_name_changed": False,
        "rn_visible_contract_changed": False,
        "rn_visible_title_changed": False,
        "display_gate_relaxed": False,
        "grounding_gate_relaxed": False,
        "template_gate_relaxed": False,
        "reader_gate_relaxed": False,
        "gate_relaxed": False,
        "raw_input_included": False,
        "raw_text_included": False,
        "comment_text_included": False,
        "comment_text_body_included": False,
        "external_ai_used": False,
        "local_llm_used": False,
        "fixed_sentence_template_used": False,
        "fixed_fallback_used": False,
        "surface_text_repaired_by_step6": False,
        "surface_text_repaired_by_step7": True,
        "fixed_sentence_template_added_by_step7": False,
        "input_specific_template_added_by_step7": False,
        "rn_complete_dedicated_display_branch_added": False,
        "complete_dedicated_rn_display_branch_added": False,
    }
    assert_runtime_surface_quality_contract_inventory_meta_only(inventory)
    return inventory


def dump_runtime_surface_quality_contract_inventory(inventory: Mapping[str, Any] | None = None) -> str:
    data = dict(inventory or build_runtime_surface_quality_contract_inventory())
    data["raw_input_included"] = False
    data["raw_text_included"] = False
    data["comment_text_included"] = False
    data["comment_text_body_included"] = False
    assert_runtime_surface_quality_contract_inventory_meta_only(data)
    return json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


__all__ = [
    "RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_STEP",
    "RUNTIME_SURFACE_QUALITY_CONTRACT_INVENTORY_VERSION",
    "RUNTIME_SURFACE_QUALITY_SCOPE",
    "assert_runtime_surface_quality_contract_inventory_meta_only",
    "build_runtime_surface_quality_contract_inventory",
    "dump_runtime_surface_quality_contract_inventory",
]
